*&---------------------------------------------------------------------*
*& Report ZALVREP3
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZALVREP3
NO STANDARD PAGE HEADING
MESSAGE-ID ZMSGCL.
*DECLARATIONS
TYPES: BEGIN OF TYPE1,
         KUNNR TYPE KNA1-KUNNR,
         NAME1 TYPE KNA1-NAME1,
         LAND1 TYPE KNA1-LAND1,
       END OF TYPE1,
       BEGIN OF TYPE2,
         EBELN TYPE VBAK-VBELN,
         AEDAT TYPE VBAK-AEDAT,
         WAERK TYPE VBAK-WAERK,
         NETWR TYPE VBAK-NETWR,
         KUNNR TYPE VBAK-KUNNR,
        END OF TYPE2.
DATA: ITAB1 TYPE TABLE OF TYPE1,
      WA1   TYPE TYPE1.
DATA:ITAB2 TYPE TABLE OF TYPE2,
     WA2 TYPE TYPE2.
*EVENT DECLARATION
TYPE-POOLS: SLIS.
DATA:ITE TYPE SLIS_T_EVENT,
     WAE TYPE SLIS_ALV_EVENT.
DATA:ITE3 TYPE SLIS_T_EVENT,
     WAE3 TYPE SLIS_ALV_EVENT.
*FIELDCAT DECLARATION
DATA: ITFCAT TYPE SLIS_T_FIELDCAT_ALV,
      WAFCAT TYPE SLIS_FIELDCAT_ALV.
DATA: ITFCAT2 TYPE SLIS_T_FIELDCAT_ALV,
      WAFCAT2 TYPE SLIS_FIELDCAT_ALV.
*INPUT
INCLUDE: ZINC10.
*PROCESS
START-OF-SELECTION.
    PERFORM SUBR_OPENSQL.
END-OF-SELECTION.
*OUTPUT
CASE SY-SUBRC.
  WHEN 0.
    PERFORM SUBR_FCAT.
    PERFORM ASSIGN_EVENT.
    PERFORM OUTPUT.
  WHEN 4.
    MESSAGE S001.
ENDCASE.
*&      Form  SUBR_OPENSQL
FORM SUBR_OPENSQL .
      SELECT KUNNR NAME1 LAND1
        INTO TABLE ITAB1 FROM KNA1
        WHERE KUNNR IN CUSTOMER.
ENDFORM.
*&      Form  SUBR_FCAT
FORM SUBR_FCAT .
  WAFCAT-COL_POS = 1.
  WAFCAT-FIELDNAME = 'KUNNR'.
  WAFCAT-KEY = 'X'.
  WAFCAT-JUST = 'C'.
  WAFCAT-OUTPUTLEN = 20.
  WAFCAT-SELTEXT_M = 'CUSTOMER NO.'.
  APPEND WAFCAT TO ITFCAT.
  CLEAR WAFCAT.

  WAFCAT-COL_POS = 2.
  WAFCAT-FIELDNAME = 'NAME1'.
  WAFCAT-KEY = 'X'.
  WAFCAT-JUST = 'C'.
  WAFCAT-OUTPUTLEN = 20.
  WAFCAT-SELTEXT_M = 'CUSTOMER NAME'.
  APPEND WAFCAT TO ITFCAT.
  CLEAR WAFCAT.

  WAFCAT-COL_POS = 3.
  WAFCAT-FIELDNAME = 'LAND1'.
  WAFCAT-KEY = 'X'.
  WAFCAT-JUST = 'C'.
  WAFCAT-OUTPUTLEN = 20.
  WAFCAT-SELTEXT_M = 'COUNTRY CODE'.
  APPEND WAFCAT TO ITFCAT.
  CLEAR WAFCAT.
ENDFORM.
*&      Form  OUTPUT
FORM OUTPUT .
     CALL FUNCTION 'REUSE_ALV_LIST_DISPLAY'
      EXPORTING
        I_CALLBACK_PROGRAM             = SY-CPROG
        IT_FIELDCAT                    = ITFCAT
        IT_EVENTS                      = ITE
       TABLES
         T_OUTTAB                       = ITAB1.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  ASSIGN_EVENT
FORM ASSIGN_EVENT.
   WAE-NAME = 'USER_COMMAND'.
   WAE-FORM = 'SUBR_EVENT'.
   APPEND WAE TO ITE.
   CLEAR WAE.
ENDFORM.
FORM SUBR_EVENT USING PV1 TYPE SY-UCOMM PV2 TYPE SLIS_SELFIELD.
     IF PV2-FIELDNAME EQ 'KUNNR'.
       CUSTOMER = PV2-VALUE.
         PERFORM SUBR_OPENSQL2.
         PERFORM SUBR_FCAT2.
           IF SY-SUBRC EQ 0.
             PERFORM SUBR_OUTPUT2.
           ELSE.
             MESSAGE S001.
           ENDIF.
    ENDIF.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SUBR_OPENSQL2
FORM SUBR_OPENSQL2 .
  CLEAR ITAB2.
     SELECT VBELN AEDAT WAERK NETWR KUNNR
       INTO TABLE ITAB2 FROM VBAK
       WHERE KUNNR IN CUSTOMER.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SUBR_FCAT2
FORM SUBR_FCAT2 .
   WAFCAT2-COL_POS = 1.
  WAFCAT2-FIELDNAME = 'VBELN'.
  WAFCAT2-KEY = 'X'.
  WAFCAT2-JUST = 'C'.
  WAFCAT2-OUTPUTLEN = 20.
  WAFCAT2-SELTEXT_M = 'ORDER NO.'.
  APPEND WAFCAT2 TO ITFCAT2.
  CLEAR WAFCAT2.

  WAFCAT2-COL_POS = 2.
  WAFCAT2-FIELDNAME = 'AEDAT'.
  WAFCAT2-KEY = 'X'.
  WAFCAT2-JUST = 'C'.
  WAFCAT2-OUTPUTLEN = 20.
  WAFCAT2-SELTEXT_M = 'ORDER DATE'.
  APPEND WAFCAT2 TO ITFCAT2.
  CLEAR WAFCAT2.

  WAFCAT2-COL_POS = 3.
  WAFCAT2-FIELDNAME = 'WAERK'.
  WAFCAT2-KEY = 'X'.
  WAFCAT2-JUST = 'C'.
  WAFCAT2-OUTPUTLEN = 20.
  WAFCAT2-SELTEXT_M = 'CURRENCY'.
  APPEND WAFCAT2 TO ITFCAT2.
  CLEAR WAFCAT2.

  WAFCAT2-COL_POS = 4.
  WAFCAT2-FIELDNAME = 'NETWR'.
  WAFCAT2-KEY = 'X'.
  WAFCAT2-JUST = 'C'.
  WAFCAT2-OUTPUTLEN = 20.
  WAFCAT2-SELTEXT_M = 'NETVALUE'.
  APPEND WAFCAT2 TO ITFCAT2.
  CLEAR WAFCAT2.

  WAFCAT2-COL_POS = 5.
  WAFCAT2-FIELDNAME = 'KUNNR'.
  WAFCAT2-KEY = 'X'.
  WAFCAT2-JUST = 'C'.
  WAFCAT2-OUTPUTLEN = 20.
  WAFCAT2-SELTEXT_M = 'SOLD TO PARTY'.
  APPEND WAFCAT2 TO ITFCAT2.
  CLEAR WAFCAT2.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SUBR_OUTPUT2
FORM SUBR_OUTPUT2 .
  CLEAR WAE.
        WAE-NAME = 'USER_COMMAND'.
        WAE-FORM = 'SUBR_EVENT3'.
        APPEND WAE TO ITE.
     CALL FUNCTION 'REUSE_ALV_LIST_DISPLAY'
      EXPORTING
        I_CALLBACK_PROGRAM             = SY-CPROG
        IT_FIELDCAT                    = ITFCAT2
        IT_EVENTS                      = ITE
       TABLES
         T_OUTTAB                       = ITAB2.
ENDFORM.
*------------------------------------------------------------------------*
*FORM SUBR_EVENT3
FORM SUBR_EVENT3 USING PV3 TYPE SY-UCOMM PV4 TYPE SLIS_SELFIELD.
     DATA: ORDERNO TYPE VBAK-VBELN.
     IF PV4-FIELDNAME EQ 'VBELN'.
        ORDERNO = PV4-VALUE.
      CALL TRANSACTION 'VA03' AND SKIP FIRST SCREEN.
     ENDIF.
ENDFORM.
