
REPORT ZALVHY1
NO STANDARD PAGE HEADING
MESSAGE-ID ZMSGCL.
*DECLARATION
TYPES: BEGIN OF TYPE1,
          VBELN TYPE VBAK-VBELN,
          NETWR TYPE VBAK-NETWR,
          WAERK TYPE VBAK-WAERK,
      END OF TYPE1.
DATA: ITAB1 TYPE TABLE OF TYPE1.
TYPES: BEGIN OF TYPE2,
        VBELN TYPE VBAP-VBELN,
        POSNR TYPE VBAP-POSNR,
        MATNR TYPE VBAP-MATNR,
       END OF TYPE2.
DATA: ITAB2 TYPE TABLE OF TYPE2.
*GLOBAL DECLARATION
TYPE-POOLS: SLIS.
*FIELDCAT DECLARATION
DATA: ITFCAT TYPE SLIS_T_FIELDCAT_ALV,
      WFCAT  LIKE LINE OF ITFCAT.
*KEYINFO DECLARATION.
DATA: KEYINFO TYPE SLIS_KEYINFO_ALV.
*INPUT
DATA: V1 TYPE VBAK-ERDAT.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
  PARAMETERS CUSTOMER TYPE VBAK-KUNNR.
SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
  SELECT-OPTIONS DATE FOR V1.
SELECTION-SCREEN END OF BLOCK B2.
*PROCESS
START-OF-SELECTION.
    PERFORM SUBR_OPENSQL.
END-OF-SELECTION.
*OUTPUT
CASE SY-SUBRC.
  WHEN 0.
    PERFORM SUBR_FCAT.
    PERFORM SUBR_KEYINFO.
    PERFORM SUBR_OUTPUT.
  WHEN 4.
    MESSAGE S003.
ENDCASE.
*&---------------------------------------------------------------------*
*&      Form  SUBR_OPENSQL
*&---------------------------------------------------------------------*
FORM SUBR_OPENSQL .
     SELECT VBELN NETWR WAERK
       INTO TABLE ITAB1 FROM VBAK
       WHERE ERDAT IN DATE.
   IF NOT ITAB1 IS INITIAL.
     SELECT VBELN POSNR MATNR
       INTO TABLE ITAB2 FROM VBAP
       FOR ALL ENTRIES IN ITAB1
       WHERE VBELN EQ ITAB1-VBELN.
   ELSE.
     MESSAGE S003.
   ENDIF.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SUBR_FCAT
*&---------------------------------------------------------------------*
FORM SUBR_FCAT .
WFCAT-FIELDNAME = 'VBELN'.
WFCAT-SELTEXT_M = 'SALES NO.'.
WFCAT-TABNAME   = 'ITAB1'.
APPEND WFCAT TO ITFCAT.
CLEAR WFCAT.

WFCAT-FIELDNAME = 'NETWR'.
WFCAT-SELTEXT_M = 'NET VALUE'.
WFCAT-TABNAME   = 'ITAB1'.
APPEND WFCAT TO ITFCAT.
CLEAR WFCAT.

WFCAT-FIELDNAME = 'WAERK'.
WFCAT-SELTEXT_M = 'CURRENCY'.
WFCAT-TABNAME   = 'ITAB1'.
APPEND WFCAT TO ITFCAT.
CLEAR WFCAT.

WFCAT-FIELDNAME = 'VBELN'.
WFCAT-SELTEXT_M = 'SALES NO.'.
WFCAT-TABNAME   = 'ITAB2'.
APPEND WFCAT TO ITFCAT.
CLEAR WFCAT.

WFCAT-FIELDNAME = 'POSNR'.
WFCAT-SELTEXT_M = 'ITEM'.
WFCAT-TABNAME   = 'ITAB2'.
APPEND WFCAT TO ITFCAT.
CLEAR WFCAT.

WFCAT-FIELDNAME = 'MATNR'.
WFCAT-SELTEXT_M = 'MATERIAL NO'.
WFCAT-TABNAME   = 'ITAB2'.
APPEND WFCAT TO ITFCAT.
CLEAR WFCAT.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SUBR_KEYINFO
*&---------------------------------------------------------------------*
FORM SUBR_KEYINFO .
   KEYINFO-HEADER01 = 'VBELN'.
   KEYINFO-ITEM01   = 'VBELN'.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SUBR_OUTPUT
*&---------------------------------------------------------------------*
FORM SUBR_OUTPUT .
     CALL FUNCTION 'REUSE_ALV_HIERSEQ_LIST_DISPLAY'
       EXPORTING
        I_CALLBACK_PROGRAM             = SY-CPROG
        IT_FIELDCAT                    = ITFCAT
         I_TABNAME_HEADER              = 'ITAB1'
         I_TABNAME_ITEM                = 'ITAB2'
         IS_KEYINFO                    = KEYINFO
        I_BYPASSING_BUFFER             = 'X'
        I_BUFFER_ACTIVE                = 'X'
       TABLES
         T_OUTTAB_HEADER                = ITAB1
         T_OUTTAB_ITEM                  = ITAB2.
ENDFORM.
