*&---------------------------------------------------------------------*
*& Report ZBLOCKREP1
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZBLOCKREP1
NO STANDARD PAGE HEADING
MESSAGE-ID ZMSGCL.
*DECLARATION
TYPES: BEGIN OF TYPE1,
         LIFNR TYPE KNA1-LIFNR,
         LAND1 TYPE KNA1-LAND1,
         NAME1 TYPE KNA1-NAME1,
       END OF TYPE1.
DATA: ITAB1 TYPE TABLE OF TYPE1.
TYPES: BEGIN OF TYPE2,
          LIFNR TYPE LFA1-LIFNR,
          ORT01 TYPE LFA1-ORT01,
          REGIO TYPE LFA1-REGIO,
          STRAS TYPE LFA1-STRAS,
       END OF TYPE2.
DATA: ITAB2 TYPE TABLE OF TYPE2.
TYPES: BEGIN OF TYPE3,
          LIFNR TYPE LFB1-LIFNR,
          BUKRS TYPE LFB1-BUKRS,
          AKONT TYPE LFB1-AKONT,
          ERDAT TYPE LFB1-ERDAT,
       END OF TYPE3.
DATA: ITAB3 TYPE TABLE OF TYPE3.
*GLOBAL DECLARATION
TYPE-POOLS: SLIS.
*FIELDCAT DECLARATION
DATA: ITFCAT1 TYPE SLIS_T_FIELDCAT_ALV,
      WAFCAT1 LIKE LINE OF ITFCAT1.
DATA: ITFCAT3 TYPE SLIS_T_FIELDCAT_ALV,
      WAFCAT3 LIKE LINE OF ITFCAT3.
DATA: ITFCAT2 TYPE SLIS_T_FIELDCAT_ALV,
      WAFCAT2 LIKE LINE OF ITFCAT2.
*EVENT DECLARATION
DATA: ITE1 TYPE SLIS_T_EVENT,
      ITE2 TYPE SLIS_T_EVENT,
      ITE3 TYPE SLIS_T_EVENT.
*LAYOUT DECLARATION
DATA: ITLAYOUT1 TYPE SLIS_LAYOUT_ALV,
      ITLAYOUT2 TYPE SLIS_LAYOUT_ALV,
      ITLAYOUT3 TYPE SLIS_LAYOUT_ALV.
*INPUT
DATA: V1 TYPE KNA1-LIFNR.
SELECTION-SCREEN BEGIN OF BLOCK B1.
  SELECT-OPTIONS VENDOR FOR V1.
SELECTION-SCREEN END OF BLOCK B1.
*PROCESS
START-OF-SELECTION.
   SELECT LIFNR LAND1 NAME1
          INTO TABLE ITAB1 FROM LFA1
          WHERE LIFNR IN VENDOR.
     IF NOT ITAB1 IS INITIAL.
        SELECT LIFNR ORT01 REGIO STRAS
               INTO TABLE ITAB2 FROM LFA1
               FOR ALL ENTRIES IN ITAB1
               WHERE LIFNR EQ ITAB1-LIFNR.
            IF NOT ITAB2 IS INITIAL.
              SELECT LIFNR BUKRS AKONT ERDAT
                INTO TABLE ITAB3 FROM LFB1
                FOR ALL ENTRIES IN ITAB2
                WHERE LIFNR EQ ITAB2-LIFNR.
                ENDIF.
            IF ITAB3 IS INITIAL.
              MESSAGE S002.
          ELSE.
             PERFORM SUBR_FIELDCAT.
              PERFORM SUBR_OUTPUT.
          ENDIF.
          ENDIF.
*OUTPUT
*&---------------------------------------------------------------------*
*&      Form  SUBR_FIELDCAT
*&---------------------------------------------------------------------*
FORM SUBR_FIELDCAT .
   WAFCAT1-FIELDNAME = 'LIFNR'.
   WAFCAT1-COL_POS = '1'.
   WAFCAT1-SELTEXT_M    = 'VENDOR NUMBER'.
   APPEND WAFCAT1 TO ITFCAT1.
   CLEAR WAFCAT1.

     WAFCAT1-FIELDNAME = 'LAND1'.
   WAFCAT1-COL_POS = '2'.
   WAFCAT1-SELTEXT_M    = 'COUNTRY'.
   APPEND WAFCAT1 TO ITFCAT1.
   CLEAR WAFCAT1.

      WAFCAT1-FIELDNAME = 'NAME1'.
   WAFCAT1-COL_POS = '3'.
   WAFCAT1-SELTEXT_M    = 'NAME'.
   APPEND WAFCAT1 TO ITFCAT1.
   CLEAR WAFCAT1.

      WAFCAT2-FIELDNAME = 'LIFNR'.
   WAFCAT2-COL_POS = '1'.
   WAFCAT2-SELTEXT_M    = 'VENDOR NUMBER'.
   APPEND WAFCAT2 TO ITFCAT2.
   CLEAR WAFCAT2.

         WAFCAT2-FIELDNAME = 'ORT01'.
   WAFCAT2-COL_POS = '2'.
   WAFCAT2-SELTEXT_M    = 'CITY'.
   APPEND WAFCAT2 TO ITFCAT2.
   CLEAR WAFCAT2.

         WAFCAT2-FIELDNAME = 'REGIO'.
   WAFCAT2-COL_POS = '3'.
   WAFCAT2-SELTEXT_M    = 'REGION'.
   APPEND WAFCAT2 TO ITFCAT2.
   CLEAR WAFCAT2.

         WAFCAT2-FIELDNAME = 'STRAS'.
   WAFCAT2-COL_POS = '4'.
   WAFCAT2-SELTEXT_M    = 'STREET NUMBER'.
   APPEND WAFCAT2 TO ITFCAT2.
   CLEAR WAFCAT2.

   WAFCAT3-FIELDNAME = 'LIFNR'.
   WAFCAT3-COL_POS = '1'.
   WAFCAT3-SELTEXT_M    = 'VENDOR NUMBER'.
   APPEND WAFCAT3 TO ITFCAT3.
   CLEAR WAFCAT3.

   WAFCAT3-FIELDNAME = 'BUKRS'.
   WAFCAT3-COL_POS = '2'.
   WAFCAT3-SELTEXT_M    = 'COMPANY CODE'.
   APPEND WAFCAT3 TO ITFCAT3.
   CLEAR WAFCAT3.

      WAFCAT3-FIELDNAME = 'AKONT'.
   WAFCAT3-COL_POS = '3'.
   WAFCAT3-SELTEXT_M    = 'ACC IN GL'.
   APPEND WAFCAT3 TO ITFCAT3.
   CLEAR WAFCAT3.

      WAFCAT3-FIELDNAME = 'ERDAT'.
   WAFCAT3-COL_POS = '4'.
   WAFCAT3-SELTEXT_M    = 'DATE'.
   APPEND WAFCAT3 TO ITFCAT3.
   CLEAR WAFCAT3.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SUBR_OUTPUT
*&---------------------------------------------------------------------*
FORM SUBR_OUTPUT .

CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_INIT'
  EXPORTING
    I_CALLBACK_PROGRAM             = SY-CPROG.

CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_APPEND'
  EXPORTING
    IS_LAYOUT                        = ITLAYOUT1
    IT_FIELDCAT                      = ITFCAT1
    I_TABNAME                        = 'ITAB1'
    IT_EVENTS                        = ITE1
  TABLES
    T_OUTTAB                         = ITAB1.

CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_APPEND'
  EXPORTING
    IS_LAYOUT                        = ITLAYOUT2
    IT_FIELDCAT                      = ITFCAT2
    I_TABNAME                        = 'ITAB2'
    IT_EVENTS                        = ITE2
  TABLES
    T_OUTTAB                         = ITAB2.

CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_APPEND'
  EXPORTING
    IS_LAYOUT                        = ITLAYOUT3
    IT_FIELDCAT                      = ITFCAT3
    I_TABNAME                        = 'ITAB3'
    IT_EVENTS                        = ITE3
  TABLES
    T_OUTTAB                         = ITAB3.

CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_DISPLAY'
 EXCEPTIONS
   PROGRAM_ERROR                 = 1
   OTHERS                        = 2.
IF SY-SUBRC NE 0.
         MESSAGE ID sy-msgid TYPE sy-msgty NUMBER sy-msgno
              WITH sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
ENDIF.
ENDFORM.
