*
REPORT ZEMPINFO.
TYPE-POOLS: ZTG03.
DATA: ITAB TYPE ZTG03_ITEMTYPE.
DATA BASIC TYPE I.
ITAB-EMPNO = 20.
ITAB-NAME = 'SRINIVASA REDDY'.
ITAB-PFNO = 8665.
ITAB-JOB = 'MANAGER'.
WRITE:/5 'EMPLOYEE NO:' COLOR 4, 20 ITAB-EMPNO COLOR 5,
      /5 'EMPLOYEE NAME:' COLOR 4, 20 ITAB-NAME COLOR 5,
      /5 'EMPLOYEE PFNO:' COLOR 4, 20 ITAB-PFNO COLOR 5,
      /5 'EMPLOYEE JOB:' COLOR 4, 20 ITAB-JOB COLOR 5.
IF ITAB-JOB EQ 'MANAGER'.
BASIC = 45000.
WRITE:/5 'MANAGER SALARY:' COLOR 6, 30 BASIC COLOR 5.
ELSEIF ITAB-JOB EQ 'CLERK'.
BASIC = 25000.
WRITE:/5 'CLERK SALARY:' COLOR 6, 30 BASIC COLOR 5.
ELSEIF ITAB-JOB EQ 'SALESMAN'.
BASIC = 20000.
WRITE:/5 'SALESMAN SALARY:' COLOR 6, 30 BASIC COLOR 5.
ENDIF.
