*&---------------------------------------------------------------------*
*&  Include           ZFOODCOURTTOP_F01
*&---------------------------------------------------------------------*
FORM SUBR_ASSIGN.
ITAB-MANDT = SY-MANDT.
ITAB-SALESID = ZFOODCOURT-SALESID.
ITAB-CSTNAME = ZFOODCOURT-CSTNAME.
ITAB-CSTID   =  ZFOODCOURT-CSTID.
ITAB-PRDTID  =  ZFOODCOURT-PRDTID.
ITAB-PRDTNAME =  ZFOODCOURT-PRDTNAME.
ITAB-QTTY     =  ZFOODCOURT-QTTY.
ITAB-PRICE    =  ZFOODCOURT-PRICE.
ITAB-CURRENCY =  ZFOODCOURT-CURRENCY.
ITAB-CRTDON   =  ZFOODCOURT-CRTDON.
ITAB-CRTDTM   =  ZFOODCOURT-CRTDTM.
ENDFORM.
FORM SUBR_CLEAR.
CLEAR ITAB.
ENDFORM.
