FUNCTION ZSALESORDER.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(FMD_VBELN) TYPE  VBAK-VBELN
*"  EXPORTING
*"     REFERENCE(FMD_ITVBAK) LIKE  VBAK STRUCTURE  VBAK
*"     REFERENCE(FMD_ITKNA1) LIKE  KNA1 STRUCTURE  KNA1
*"  TABLES
*"      FMD_ITVBAP STRUCTURE  VBAP
*"  EXCEPTIONS
*"      NOTFOUND
*"----------------------------------------------------------------------
  SELECT *
      INTO FMD_ITVBAK FROM VBAK WHERE VBELN EQ FMD_VBELN.
  ENDSELECT.
  IF SY-SUBRC EQ 0.
    SELECT *
      INTO FMD_ITKNA1 FROM KNA1 WHERE KUNNR EQ FMD_ITVBAK-KUNNR.
    ENDSELECT.
  ENDIF.
  IF SY-SUBRC EQ 0.
    SELECT *
      INTO FMD_ITVBAP FROM VBAP WHERE VBELN EQ FMD_VBELN.
    ENDSELECT.
  ELSE.
    RAISE NOTFOUND.
  ENDIF.
ENDFUNCTION.
