FUNCTION ZPURCHASEORDERFMD.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(FMD_EBELN) TYPE  EKKO-EBELN
*"  EXPORTING
*"     REFERENCE(FMD_ITEKKO) LIKE  EKKO STRUCTURE  EKKO
*"     REFERENCE(FMD_ITLFA1) LIKE  LFA1 STRUCTURE  LFA1
*"  TABLES
*"      FMD_ITEKPO STRUCTURE  EKPO
*"  EXCEPTIONS
*"      NOTFOUND
*"----------------------------------------------------------------------
SELECT *
  INTO FMD_ITEKKO FROM EKKO WHERE EBELN EQ FMD_EBELN.
ENDSELECT.
IF SY-SUBRC EQ 0.
  SELECT *
    INTO FMD_ITLFA1 FROM LFA1 WHERE LIFNR EQ FMD_ITEKKO-LIFNR.
  ENDSELECT.
ENDIF.
IF SY-SUBRC EQ 0.
  SELECT *
    INTO FMD_ITEKPO FROM EKPO WHERE EBELN EQ FMD_EBELN.
  ENDSELECT.
ELSE.
  RAISE NOTFOUND.
ENDIF.
ENDFUNCTION.
