
REPORT ZFUNCMODVENDOR.
DATA: VNAME1 TYPE LFA1-NAME1,
      VPSTLZ TYPE LFA1-PSTLZ,
      VLAND1 TYPE LFA1-LAND1,
      VTELF1 TYPE LFA1-TELF1,
      VORT01 TYPE LFA1-ORT01.
PARAMETERS: VENDOR TYPE LFA1-LIFNR OBLIGATORY.
START-OF-SELECTION.
CALL FUNCTION 'ZFUNCMOD'
  EXPORTING
    FMD_LIFNR       =  VENDOR
 IMPORTING
   FMD_NAME1       =   VNAME1
   FMD_PSTLZ       =   VPSTLZ
   FMD_LAND1       =   VLAND1
   FMD_TELF1       =   VTELF1
   FMD_ORT01       =   VORT01
 EXCEPTIONS
   NOTFOUND        = 1
   OTHERS          = 2.
CASE SY-SUBRC.
  WHEN 0.
    PERFORM SUBR_OUTPUT.
  WHEN 1.
    MESSAGE 'VENDOR NOT FOUND' TYPE 'S'.
  WHEN 2.
    MESSAGE 'TRY AGAIN' TYPE 'A'.
ENDCASE.
FORM SUBR_OUTPUT.
  WRITE:/5 'VENDOR DATA' , VENDOR COLOR 4,
        /5 'NAME' , VNAME1 COLOR 4,
        /5 'POSTAL CODE', VPSTLZ COLOR 4,
        /5 'COUNTRY CODE', VLAND1 COLOR 4,
        /5 'TELEPHONE NUMBER', VTELF1 COLOR 4,
        /5 'CITY', VORT01 COLOR 4.
ENDFORM.
