*
*
REPORT ZINC1.
DATA: JOBCODE TYPE CHAR4, BASIC TYPE P.
PARAMETERS: PMGR RADIOBUTTON GROUP JOB,
            AMGR RADIOBUTTON GROUP JOB,
            FCON RADIOBUTTON GROUP JOB,
            ACON RADIOBUTTON GROUP JOB.
INCLUDE: ZINCLUDE1.
START-OF-SELECTION.
IF PMGR EQ 'X'.
  JOBCODE = 'PMGR'.
ELSEIF AMGR EQ 'X'.
  JOBCODE = 'AMGR'.
ELSEIF FCON EQ 'X'.
  JOBCODE = 'FCON'.
ELSEIF ACON EQ 'X'.
  JOBCODE = 'ACON'.
ENDIF.
 PERFORM SUBR USING JOBCODE CHANGING BASIC.
IF PMGR EQ 'X'.
  WRITE:/5 'PMGR PROJECT MANAGER'.
ELSEIF AMGR EQ 'X'.
  WRITE:/5 'AMGR ASSOCIATE MANAGER'.
ELSEIF FCON EQ 'X'.
  WRITE:/5 'FUNCTIONAL CONSULTANT'.
ELSEIF ACON EQ 'X'.
  WRITE:/5 'ABAP CONSULTANT'.
ENDIF.
WRITE:/5 'BASIC SALARY:', BASIC COLOR 4.
