*&---------------------------------------------------------------------*
*&  Include           ZINC5
*&---------------------------------------------------------------------*
DATA: V1 TYPE EKKO-AEDAT.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE T1.
  PARAMETERS VENDOR TYPE EKKO-LIFNR.
SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE T2.
  SELECT-OPTIONS PODATE FOR V1 OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B2.
INITIALIZATION.
T1 = 'VENDOR NUMBER'.
T2 = 'PURCHASE ORDER DATE'.
