*&---------------------------------------------------------------------*
*&  Include           ZINC3
*&---------------------------------------------------------------------*
DATA: V1 TYPE KNA1-KUNNR.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE T1.
  SELECT-OPTIONS CUSTOMER FOR V1 OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE T2.
  PARAMETERS COUNTRY TYPE KNA1-LAND1 .
SELECTION-SCREEN END OF BLOCK B2.
INITIALIZATION.
T1 = 'CUSTOMER NUMBER'.
T2 = 'COUNTRY CODE'.
