*&---------------------------------------------------------------------*
*&  Include           ZINC4
*&---------------------------------------------------------------------*
DATA: V1 TYPE VBAK-ERDAT,
      V2 TYPE VBAK-KUNNR.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE T1.
  SELECT-OPTIONS DATE FOR V1.
SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE T2.
  SELECT-OPTIONS CUSTOMER FOR V2 OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B2.
INITIALIZATION.
T1 = 'SALES ORDER DATE'.
T2 = 'SOLD TO PARTY'.
