*
REPORT ZLEFTOUTERJOIN.
TYPES: BEGIN OF TYPE1,
         LIFNR TYPE LFA1-LIFNR,    "VENDOR NO"
         LAND1 TYPE LFA1-LAND1,    "COUNTRY KEY"
         NAME1 TYPE LFA1-NAME1,    "NAME1"
         NAME2 TYPE LFA1-NAME2,    "NAME2"
         TELF1 TYPE LFA1-TELF1,    "TELEPHONE NO"
         EBELN TYPE EKKO-EBELN,    "PO NO"
         BUKRS TYPE EKKO-BUKRS,    "COMPANY CODE"
         BSART TYPE EKKO-BSART,    "PO DOC TYPE"
         STATU TYPE EKKO-STATU,    "PO DOC STATUS"
         BEDAT TYPE EKKO-BEDAT,    "PO DATE"
       END OF TYPE1,
       BEGIN OF TYPE2,
         LIFNR TYPE LFA1-LIFNR,
         LAND1 TYPE LFA1-LAND1,
         NAME1 TYPE LFA1-NAME1,
         NAME2 TYPE LFA1-NAME2,
         TELF1 TYPE LFA1-TELF1,
       END OF TYPE2,
       BEGIN OF TYPE3,
         EBELN TYPE EKKO-EBELN,
         BUKRS TYPE EKKO-BUKRS,
         BSART TYPE EKKO-BSART,
         STATU TYPE EKKO-STATU,
         BEDAT TYPE EKKO-BEDAT,
       END OF TYPE3.
DATA: ITAB1 TYPE TABLE OF TYPE1,
      WA1 TYPE TYPE1,
      ITAB2 TYPE TABLE OF TYPE2,
      WA2 TYPE TYPE2,
      ITAB3 TYPE TABLE OF TYPE3,
      WA3 TYPE TYPE3.
DATA VLIFNR TYPE LFA1-LIFNR.
SELECT-OPTIONS VENDOR FOR VLIFNR OBLIGATORY.
START-OF-SELECTION.
    SELECT A~LIFNR A~LAND1 A~NAME1 A~NAME2 A~TELF1
           B~EBELN B~BUKRS B~BSART B~STATU B~BEDAT
      INTO TABLE ITAB1 FROM
      LFA1 AS A
      LEFT OUTER JOIN
      EKKO AS B
      ON A~LIFNR = B~EBELN
      WHERE A~LIFNR IN VENDOR.

IF SY-SUBRC NE 0.
  MESSAGE 'DATA NOT FOUND' TYPE 'S'.
ELSE.
  LOOP AT ITAB1 INTO WA1.
    IF WA1-LIFNR EQ SPACE.
    "PURCHASE NOT FOUND: SUBSTITUTE INTO WA2 ADD INTO ITAB2
    MOVE-CORRESPONDING WA1 TO WA2.
    APPEND WA2 TO ITAB2.
    CLEAR WA2.
    ELSE.
    MOVE-CORRESPONDING WA2 TO WA3.
    APPEND WA3 TO ITAB3.
    CLEAR WA3.
    ENDIF.
    CLEAR WA1.
  ENDLOOP.
  WRITE:/5 'VENDOR INFO NO PURCHASE ORDER FOUND.'.
  SORT ITAB2 BY LIFNR.
  LOOP AT ITAB2 INTO WA2.
    WRITE:/5 WA2-LIFNR COLOR 3, 20 WA2-LAND1 COLOR 3, 40 WA2-NAME1 COLOR 3, 60 WA2-NAME2 COLOR 3, 90 WA2-TELF1 COLOR 3.
    CLEAR WA2.
  ENDLOOP.
  WRITE:/5 'VENDOR INFO PURCHASES ORDER FOUND.' .
  SORT ITAB3 BY EBELN.
  LOOP AT ITAB3 INTO WA3.
    WRITE:/5 WA3-EBELN COLOR 3, 20 WA3-BUKRS COLOR 3, 40 WA3-BSART COLOR 3, 60 WA3-STATU COLOR 3, 90 WA3-BEDAT COLOR 3.
    CLEAR WA3.
  ENDLOOP.
  ENDIF.
