*&---------------------------------------------------------------------*
*DISPLAY MATERIAL INFO INTERNAL TABLE WITH FIELDS MATERIAL NAME,QUANTITY, UNITRATE
*STORE THE INFORMATION INTO IT, DISPLAY ITEM INFO FROM IT
*CALULATE THE AMOUNT AS QUANTITY * UNITRATE AND DISPLAY THE TOTAL AMOUNT
REPORT ZMATEINFO.
DATA:  BEGIN OF ITAB,
       MATERIALNAME TYPE CHAR16,
       QUANTITY TYPE P,
       UNITRATE TYPE P,
      END OF ITAB.
*STORE INFO
ITAB-MATERIALNAME = 'WHEAT'.
ITAB-QUANTITY = '20'.
ITAB-UNITRATE = '8'.
*DISPLAY THE INFO
WRITE:/5 'MATERIAL INFO' COLOR 4.
WRITE:/5 'MATERIAL NAME:', 20 ITAB-MATERIALNAME COLOR 5,
      /5 'QUANTITY', 20 ITAB-QUANTITY COLOR 5,
      /5 'UNIT RATE', 20 ITAB-UNITRATE COLOR 7.
DATA: AMT TYPE P.
AMT = ITAB-QUANTITY * ITAB-UNITRATE.
WRITE:/5 'TOTAL AMOUNT' , 20 AMT COLOR 2.
