PROCESS BEFORE OUTPUT.
CALL SUBSCREEN SUBSCA1 INCLUDING 'ZMDPVBAKKNA1' '0201'.
CALL SUBSCREEN SUBSCA2 INCLUDING 'ZMDPVBAKKNA1' '0202'.
MODULE STATUS_0100.

PROCESS AFTER INPUT.
MODULE USER_COMMAND_0100.
