*
REPORT ZSELECTWITHOUTENDSELECT.
TYPES: BEGIN OF TYPE,
        EBELN TYPE EKKO-EBELN,
        AEDAT TYPE EKKO-AEDAT,
        BSART TYPE EKKO-BSART,
        STATU TYPE EKKO-STATU,
        BUKRS TYPE EKKO-BUKRS,
        LIFNR TYPE EKKO-LIFNR,
      END OF TYPE.
DATA: ITAB TYPE TABLE OF TYPE,
      WA TYPE TYPE.
DATA V1 TYPE EKKO-AEDAT.
SELECT-OPTIONS PODATE FOR V1 OBLIGATORY.
START-OF-SELECTION.
    SELECT EBELN AEDAT BSART STATU BUKRS LIFNR
      INTO TABLE ITAB FROM EKKO
      WHERE AEDAT IN PODATE AND AEDAT BETWEEN PODATE-LOW AND PODATE-HIGH.

IF SY-SUBRC NE 0.
  MESSAGE 'DATA NOT FOUND' TYPE 'S'.
ELSE.
  SORT ITAB BY AEDAT.
  LOOP AT ITAB INTO WA.
    WRITE:/5 WA-EBELN COLOR 3,40 WA-AEDAT COLOR 3, 60 WA-BSART COLOR 3, 90 WA-STATU COLOR 3, 110 WA-BUKRS COLOR 3,
             200 WA-LIFNR COLOR 3.
  ENDLOOP.
ENDIF.
