*
REPORT ZSELECTWITHCOUNT.
DATA: BEGIN OF ITAB,
         EBELN TYPE EKKO-EBELN,
         BEDAT TYPE EKKO-BEDAT,
         BSART TYPE EKKO-BSART,
         STATU TYPE EKKO-STATU,
         BUKRS TYPE EKKO-BUKRS,
       END OF ITAB.
DATA VCOUNT TYPE I.
DATA V1 TYPE EKKO-BEDAT.
SELECT-OPTIONS PODATE FOR V1 OBLIGATORY.
START-OF-SELECTION.
      SELECT COUNT(*)
        INTO VCOUNT FROM EKKO
        WHERE BEDAT IN PODATE.
IF SY-SUBRC EQ 0.
  WRITE:/5 'PURCHASES FOUND THAT ARE GENERATED IN EKKO', VCOUNT COLOR 5.
  WRITE:/5 ITAB-EBELN COLOR 4, 20 ITAB-BSART COLOR 2, 40 ITAB-STATU COLOR 1, 60 ITAB-BUKRS COLOR 4, 80 ITAB-BEDAT COLOR 6.
ELSE.
  MESSAGE 'PURCHASE NOT FOUND' TYPE 'S'.
ENDIF.
