*sorted internal table
REPORT ZSORTED.
TYPE-POOLS: Z2721.
DATA: ITAB TYPE SORTED TABLE OF Z2721_ITEMTYPE WITH NON-UNIQUE KEY ITEM.
DATA WA TYPE Z2721_ITEMTYPE.
*STORE INFO
WA-ITEM = 'DIARY MILK'. WA-QUANTITY = 50. WA-UNITRATE = 1250 / 100.
INSERT WA INTO TABLE ITAB.
CLEAR WA.
WA-ITEM = '5 STAR'. WA-QUANTITY = 100. WA-UNITRATE = 3050 / 100.
INSERT WA INTO TABLE ITAB.
CLEAR WA.
WA-ITEM = 'FUSE'. WA-QUANTITY = 200. WA-UNITRATE = 2050 / 100.
INSERT WA INTO TABLE ITAB.
CLEAR WA.
WA-ITEM = 'SNICKERS'. WA-QUANTITY = 500. WA-UNITRATE = 22550 / 100.
INSERT WA INTO TABLE ITAB.
CLEAR WA.
*DISPLAY INFO
LOOP AT ITAB INTO WA.
WRITE:/5 WA-ITEM COLOR 4, 40 WA-QUANTITY COLOR 5, 55 WA-UNITRATE COLOR 6.
CLEAR WA.
ENDLOOP.
