*
REPORT ZSWESEKKO.
TYPES: BEGIN OF TYPE1,
         EBELN TYPE EKKO-EBELN,    "PO NO"
         BEDAT TYPE EKKO-BEDAT,    "PO DATE"
         BSART TYPE EKKO-BSART,    "PO DOC. TYPE"
         STATU TYPE EKKO-STATU,    "PO DOC. STATUS"
         BUKRS TYPE EKKO-BUKRS,    "COMPANY CODE"
         LIFNR TYPE EKKO-LIFNR,    "VENDOR NO"
       END OF TYPE1.
DATA: ITAB TYPE TABLE OF TYPE1,
      WA TYPE TYPE1.
DATA V1 TYPE EKKO-BEDAT.
SELECT-OPTIONS DATE FOR V1 OBLIGATORY.
START-OF-SELECTION.
      SELECT EBELN BEDAT BSART STATU BUKRS LIFNR
        INTO TABLE ITAB FROM EKKO
        WHERE BEDAT BETWEEN DATE-LOW AND DATE-HIGH.

IF SY-SUBRC NE 0.
  MESSAGE 'DATA NOT FOUND' TYPE 'S'.
ELSE.
SORT ITAB BY BEDAT.
LOOP AT ITAB INTO WA.
  WRITE:/5 WA-LIFNR COLOR 4, 20 WA-BEDAT COLOR 4, 40 WA-BSART COLOR 4, 60 WA-STATU COLOR 4, 90 WA-BUKRS COLOR 4.
        CLEAR WA.
ENDLOOP.
ENDIF.
