*&---------------------------------------------------------------------*
*& Module Pool       ZTABSTRIP
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
PROGRAM ZTABSTRIP.

*&SPWIZARD: FUNCTION CODES FOR TABSTRIP 'TSTRIP'
CONSTANTS: BEGIN OF C_TSTRIP,
             TAB1 LIKE SY-UCOMM VALUE 'TSTRIP_FC1',
             TAB2 LIKE SY-UCOMM VALUE 'TSTRIP_FC2',
           END OF C_TSTRIP.
*&SPWIZARD: DATA FOR TABSTRIP 'TSTRIP'
CONTROLS:  TSTRIP TYPE TABSTRIP.
DATA:      BEGIN OF G_TSTRIP,
             SUBSCREEN   LIKE SY-DYNNR,
             PROG        LIKE SY-REPID VALUE 'ZTABSTRIP',
             PRESSED_TAB LIKE SY-UCOMM VALUE C_TSTRIP-TAB1,
           END OF G_TSTRIP.
DATA:      OK_CODE LIKE SY-UCOMM.

*&SPWIZARD: OUTPUT MODULE FOR TS 'TSTRIP'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: SETS ACTIVE TAB
MODULE TSTRIP_ACTIVE_TAB_SET OUTPUT.
  TSTRIP-ACTIVETAB = G_TSTRIP-PRESSED_TAB.
  CASE G_TSTRIP-PRESSED_TAB.
    WHEN C_TSTRIP-TAB1.
      G_TSTRIP-SUBSCREEN = '0101'.
    WHEN C_TSTRIP-TAB2.
      G_TSTRIP-SUBSCREEN = '0102'.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TS 'TSTRIP'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: GETS ACTIVE TAB
MODULE TSTRIP_ACTIVE_TAB_GET INPUT.
  OK_CODE = SY-UCOMM.
  CASE OK_CODE.
    WHEN C_TSTRIP-TAB1.
      G_TSTRIP-PRESSED_TAB = C_TSTRIP-TAB1.
    WHEN C_TSTRIP-TAB2.
      G_TSTRIP-PRESSED_TAB = C_TSTRIP-TAB2.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.
TABLES:KNA1.
DATA: BEGIN OF ITAB,
       KUNNR TYPE KNA1-KUNNR,
       NAME1 TYPE KNA1-NAME1,
       NAME2 TYPE KNA1-NAME2,
       LAND1 TYPE KNA1-LAND1,
       STRAS TYPE KNA1-STRAS,
       ORT01 TYPE KNA1-ORT01,
       PSTLZ TYPE KNA1-PSTLZ,
       REGIO TYPE KNA1-REGIO,
       TELFX TYPE KNA1-TELFX,
      END OF ITAB.

MODULE USER_COMMAND_0100 INPUT.
 CASE SY-UCOMM.
    WHEN 'FIND'.
     IF SY-SUBRC EQ 0.
      SELECT KUNNR NAME1 NAME2 LAND1 STRAS ORT01 PSTLZ REGIO TELFX
             INTO ITAB FROM KNA1
             WHERE KUNNR EQ KNA1-KUNNR.
      ENDSELECT.
     ELSE.
       MESSAGE 'CUSTOMER NOT FOUND' TYPE 'S'.
       CLEAR ITAB.
    ENDIF.
    WHEN 'EXIT'.
       LEAVE PROGRAM.
ENDCASE.
ENDMODULE.
*&---------------------------------------------------------------------*
*&      Module  STATUS_0110  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_0110 OUTPUT.
 MOVE-CORRESPONDING ITAB TO KNA1.
ENDMODULE.
