PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'TSTRIP'
  MODULE TSTRIP_ACTIVE_TAB_SET.
  CALL SUBSCREEN:
       0101_SCA INCLUDING G_TSTRIP-PROG '0101',
       0102_SCA INCLUDING G_TSTRIP-PROG '0102'.
* MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'TSTRIP'
  CALL SUBSCREEN:
       0101_SCA,
       0102_SCA.
  MODULE TSTRIP_ACTIVE_TAB_GET.
 MODULE USER_COMMAND_0100.
