*&---------------------------------------------------------------------*
*& Report Z_ALVITREP2
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT Z_ALVITREP2
NO STANDARD PAGE HEADING
MESSAGE-ID ZMSGCL.
*DECLARATIONS
TYPES: BEGIN OF TYPE1,
          EBELN TYPE EKKO-EBELN,
          AEDAT TYPE EKKO-AEDAT,
          BSART TYPE EKKO-BSART,
          STATU TYPE EKKO-STATU,
          BUKRS TYPE EKKO-BUKRS,
          LIFNR TYPE EKKO-LIFNR,
      END OF TYPE1.
DATA: ITAB1 TYPE TABLE OF TYPE1,
      WA1   TYPE TYPE1.
DATA: ITAB2 TYPE TABLE OF EKKO,
      ITAB3 TYPE TABLE OF EKKO.
TYPE-POOLS:SLIS.
DATA:ITFCAT TYPE SLIS_T_FIELDCAT_ALV,
     WAFCAT TYPE SLIS_FIELDCAT_ALV.
*EVENTS
DATA: ITE TYPE SLIS_T_EVENT,
      WAE TYPE SLIS_ALV_EVENT.
*INPUT
INCLUDE: ZINC8.
*PROCESS
START-OF-SELECTION.
   PERFORM SUBR_OPENSQL.
END-OF-SELECTION.
*OUTPUT
CASE SY-SUBRC.
   WHEN 0.
     PERFORM SUBR_FIELDCAT.
     PERFORM ASSIGN_EVENT.
     PERFORM SUBR_OUTPUT1.
   WHEN 4.
     MESSAGE S002.
ENDCASE.
*&      Form  SUBR_OPENSQL
FORM SUBR_OPENSQL .
     SELECT EBELN AEDAT BSART STATU BUKRS LIFNR
       INTO TABLE ITAB1 FROM EKKO
       WHERE LIFNR EQ VENDOR.
ENDFORM.
*&      Form  SUBR_FIELDCAT
FORM SUBR_FIELDCAT .
  WAFCAT-COL_POS = 1.
  WAFCAT-FIELDNAME = 'EBELN'.
  WAFCAT-KEY = 'X'.
  WAFCAT-JUST = 'C'.
  WAFCAT-OUTPUTLEN = 20.
  WAFCAT-SELTEXT_M = 'PURCHASE ORDER NO.'.
  APPEND WAFCAT TO ITFCAT.
  CLEAR WAFCAT.

  WAFCAT-COL_POS = 2.
  WAFCAT-FIELDNAME = 'AEDAT'.
  WAFCAT-KEY = 'X'.
  WAFCAT-JUST = 'C'.
  WAFCAT-OUTPUTLEN = 20.
  WAFCAT-SELTEXT_M = 'PO DATE'.
  APPEND WAFCAT TO ITFCAT.
  CLEAR WAFCAT.

  WAFCAT-COL_POS = 3.
  WAFCAT-FIELDNAME = 'BSART'.
  WAFCAT-KEY = 'X'.
  WAFCAT-JUST = 'C'.
  WAFCAT-OUTPUTLEN = 20.
  WAFCAT-SELTEXT_M = 'ORDER DOC. TYPE'.
  APPEND WAFCAT TO ITFCAT.
  CLEAR WAFCAT.

  WAFCAT-COL_POS = 4.
  WAFCAT-FIELDNAME = 'STATU'.
  WAFCAT-KEY = 'X'.
  WAFCAT-JUST = 'C'.
  WAFCAT-OUTPUTLEN = 20.
  WAFCAT-SELTEXT_M = 'ORDER DOC. STATUS'.
  APPEND WAFCAT TO ITFCAT.
  CLEAR WAFCAT.

  WAFCAT-COL_POS = 5.
  WAFCAT-FIELDNAME = 'BUKRS'.
  WAFCAT-KEY = 'X'.
  WAFCAT-JUST = 'C'.
  WAFCAT-OUTPUTLEN = 20.
  WAFCAT-SELTEXT_M = 'COMPANY CODE'.
  APPEND WAFCAT TO ITFCAT.
  CLEAR WAFCAT.

  WAFCAT-COL_POS = 6.
  WAFCAT-FIELDNAME = 'LIFNR'.
  WAFCAT-KEY = 'X'.
  WAFCAT-JUST = 'C'.
  WAFCAT-OUTPUTLEN = 20.
  WAFCAT-SELTEXT_M = 'VENDOR NO'.
  APPEND WAFCAT TO ITFCAT.
  CLEAR WAFCAT.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SUBR_OUTPUT1
FORM SUBR_OUTPUT1 .
CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
 EXPORTING
   I_CALLBACK_PROGRAM                = SY-CPROG
   I_GRID_TITLE                      = 'PURCHASE ORDER HEADER DATA'
   IT_EVENTS                         = ITE
  TABLES
    T_OUTTAB                          = ITAB1.
ENDFORM.
*&      Form  ASSIGN_EVENT
FORM ASSIGN_EVENT .

ENDFORM.
