*&---------------------------------------------------------------------*
*&  Include           ZFOODCOURTTOP_I01
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_0100  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_0100 INPUT.
OKCODE = SY-UCOMM.
CASE OKCODE.
WHEN 'CREATE'.
IF ZFOODCOURT EQ SPACE.
MESSAGE 'ENTER THE SALES ID REQUIRED' TYPE 'I'.
ELSEIF ZFOODCOURT-CSTNAME EQ SPACE.
MESSAGE 'CUSTOMER NAME REQUIRED' TYPE 'I'.
ELSEIF ZFOODCOURT-CSTID EQ SPACE.
MESSAGE 'CUSTOMER IF REQUIRED' TYPE 'I'.
ELSEIF ZFOODCOURT-PRDTID EQ SPACE.
MESSAGE 'PRODUCT ID REQUIRED ' TYPE 'I'.
ELSEIF ZFOODCOURT-PRDTNAME EQ SPACE.
MESSAGE 'PRODUCT NAME REQUIRED' TYPE 'I'.
ELSEIF ZFOODCOURT-QTTY EQ SPACE.
MESSAGE 'QUANTITY REQUIRED' TYPE 'I'.
ELSEIF ZFOODCOURT-PRICE EQ SPACE.
MESSAGE 'PRICE IS REQUIRED' TYPE 'I'.
ELSEIF ZFOODCOURT-CURRENCY EQ SPACE.
MESSAGE 'CURRENCY IS REQUIRED' TYPE'I'.
ELSEIF ZFOODCOURT-CRTDON EQ SPACE.
MESSAGE 'CREATED DATE REQUIRED' TYPE'I'.
ELSEIF ZFOODCOURT-CRTDTM EQ SPACE.
MESSAGE 'CREATED TIME REQUIRED' TYPE 'I'.
ELSE.
PERFORM SUBR_ASSIGN.
INSERT ZFOODCOURT FROM ITAB.
IF SY-SUBRC EQ 0.
MESSAGE 'NEW SALES INFORMATION SAVED SUCESSFULLY' TYPE 'I'.
PERFORM SUBR_CLEAR.
ELSE.
MESSAGE 'SAVE FAILED......ENTRY EXSIST' TYPE 'I'.
ENDIF.
ENDIF.
WHEN'FIND'.
SELECT SINGLE * FROM ZFOODCOURT WHERE SALESID = ZFOODCOURT-SALESID.
IF SY-SUBRC NE 0.
MESSAGE 'SALES DATA NOT FOUND' TYPE 'I'.
PERFORM SUBR_CLEAR.
ENDIF.
WHEN'UPDATE'.
IF ZFOODCOURT-SALESID EQ SPACE.
MESSAGE 'WITHOUT SALESID UPDATE CANNOT BE DONE' TYPE 'I'.
ELSE.
PERFORM SUBR_ASSIGN.
UPDATE ZFOODCOURT FROM ITAB.
ENDIF.
IF SY-SUBRC EQ 0.
MESSAGE 'UPDATED SUCESSFULLY ' TYPE 'I'.
PERFORM SUBR_CLEAR.
ELSE.
MESSAGE 'UPDATE FAILED ' TYPE 'I'.
PERFORM SUBR_CLEAR.
ENDIF.
WHEN 'DELETE'.
IF ZFOODCOURT-SALESID EQ SPACE.
MESSAGE 'WITHOUT SALESID DELETE CANOOT BE DONE' TYPE 'I'.
PERFORM SUBR_CLEAR.
ELSE.
CALL SCREEN '0200' STARTING AT 50 10 ENDING AT 90 13.
ENDIF.
WHEN 'EXIT'.
LEAVE PROGRAM.
ENDCASE.
ENDMODULE.
*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_0200  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_0200 INPUT.
OKCODE = SY-UCOMM.
CASE OKCODE.
WHEN 'YES'.
DELETE FROM ZFOODCOURT WHERE SALESID EQ ZFOODCOURT-SALESID.
IF SY-SUBRC EQ 0.
MESSAGE 'SALES DATA DELETED' TYPE 'I'.
PERFORM SUBR_CLEAR.
ELSE.
MESSAGE 'DELETE FAILED' TYPE 'I'.
PERFORM SUBR_CLEAR.
CALL SCREEN '0100'.
ENDIF.
WHEN 'NO'.
PERFORM SUBR_CLEAR.
CALL SCREEN '0100'.
ENDCASE.
ENDMODULE.
