FUNCTION ZFOODCOURTFM.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(FMD_SALESID) TYPE  ZFOODCOURT-SALESID
*"  EXPORTING
*"     REFERENCE(FMD_CSTNAME) TYPE  ZFOODCOURT-CSTNAME
*"     REFERENCE(FMD_PRDTNAME) TYPE  ZFOODCOURT-PRDTNAME
*"     REFERENCE(FMD_QTTY) TYPE  ZFOODCOURT-QTTY
*"     REFERENCE(FMD_PRICE) TYPE  ZFOODCOURT-PRICE
*"     REFERENCE(FMD_CRTDON) TYPE  ZFOODCOURT-CRTDON
*"     REFERENCE(FMD_CRTDTM) TYPE  ZFOODCOURT-CRTDTM
*"  EXCEPTIONS
*"      NOTFOUND
*"----------------------------------------------------------------------
  TYPES: BEGIN OF TYPE1,
            CSTNAME TYPE ZFOODCOURT-CSTNAME,
            PRDTNAME TYPE ZFOODCOURT-PRDTNAME,
            QTTY TYPE ZFOODCOURT-QTTY,
            PRICE TYPE ZFOODCOURT-PRICE,
            CRTDON TYPE ZFOODCOURT-CRTDON,
            CRTDTM TYPE ZFOODCOURT-CRTDTM,
        END OF TYPE1.
  data: ITAB TYPE TYPE1.

  SELECT CSTNAME PRDTNAME QTTY PRICE CRTDON CRTDTM INTO ITAB FROM ZFOODCOURT WHERE SALESID EQ FMD_SALESID.
    ENDSELECT.
    IF SY-SUBRC EQ 0.
      FMD_CSTNAME = ITAB-CSTNAME.
      FMD_PRDTNAME = ITAB-PRDTNAME.
      FMD_QTTY = ITAB-QTTY.
      FMD_PRICE = ITAB-PRICE.
      FMD_CRTDON = ITAB-CRTDON.
      FMD_CRTDTM = ITAB-CRTDTM.
      ELSE.
        RAISE NOTFOUND.
        ENDIF.


ENDFUNCTION.
