FUNCTION ZFUNCMOD.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(FMD_LIFNR) TYPE  LFA1-LIFNR
*"  EXPORTING
*"     REFERENCE(FMD_NAME1) TYPE  LFA1-NAME1
*"     REFERENCE(FMD_PSTLZ) TYPE  LFA1-PSTLZ
*"     REFERENCE(FMD_LAND1) TYPE  LFA1-LAND1
*"     REFERENCE(FMD_TELF1) TYPE  LFA1-TELF1
*"     REFERENCE(FMD_ORT01) TYPE  LFA1-ORT01
*"  EXCEPTIONS
*"      NOTFOUND
*"----------------------------------------------------------------------
TYPES: BEGIN OF TYPE1,
        NAME1 TYPE LFA1-NAME1,
        PSTLZ TYPE LFA1-PSTLZ,
        LAND1 TYPE LFA1-LAND1,
        TELF1 TYPE LFA1-TELF1,
        ORT01 TYPE LFA1-ORT01,
      END OF TYPE1.
DATA: ITAB TYPE TYPE1.
SELECT NAME1 PSTLZ LAND1 TELF1 ORT01
       INTO ITAB FROM LFA1
       WHERE LIFNR EQ FMD_LIFNR.
ENDSELECT.
IF SY-SUBRC EQ 0.
  FMD_NAME1 = ITAB-NAME1.
  FMD_PSTLZ = ITAB-PSTLZ.
  FMD_LAND1 = ITAB-LAND1.
  FMD_TELF1 = ITAB-TELF1.
  FMD_ORT01 = ITAB-ORT01.
ELSE.
  RAISE NOTFOUND.
ENDIF.
ENDFUNCTION.
