FUNCTION ZBAPI_FUNCMOD1.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(BAPI_CUST) TYPE  KNA1-KUNNR
*"     VALUE(BAPI_TODATE) TYPE  KNA1-ERDAT
*"     VALUE(BAPI_ENDDATE) TYPE  KNA1-ERDAT
*"  EXPORTING
*"     VALUE(RETURN) TYPE  BAPIRET2
*"  TABLES
*"      BAPI_CST STRUCTURE  ZBAPISTRUCT
*"  EXCEPTIONS
*"      NOTFOUND
*"----------------------------------------------------------------------
SELECT KUNNR LAND1 NAME1 ORT01 PSTLZ TELF1 ERDAT
  INTO TABLE BAPI_CST FROM KNA1
  WHERE KUNNR EQ BAPI_CUST AND ERDAT BETWEEN BAPI_TODATE AND BAPI_ENDDATE.
  IF SY-SUBRC NE 0.
    RAISE NOTFOUND.
  ENDIF.
ENDFUNCTION.
